Repository FE3-part4-team2/-Nomad, pull requests merged in 2024-04, with the labels that each got.

#2 [Feat] 버튼 공통 컴포넌트 작성
  src/components/Button/Button.tsx
  src/components/Button/button.module.scss
  src/styles/Home.module.css
  src/styles/Home.module.scss
  src/styles/_variables.scss
  src/types/type.ts
Labels: design

#8 [Feat] 헤더, 푸터 생성
  public/assets/images/.gitkeep
  public/assets/images/facebook.svg
  public/assets/images/instagram.png
  public/assets/images/logo.png
  public/assets/images/twitter.svg
  public/assets/images/youtube.png
  src/components/Footer/Footer.tsx
  src/components/Footer/footer.module.scss
  src/components/Header/Header.tsx
  src/components/Header/header.module.scss
  src/pages/index.tsx
  src/styles/globals.css
Labels: design

#11 [Feat] : Toast 기능 추가
  package-lock.json
  package.json
  src/components/Toast/Toast.tsx
  src/components/logo/index.html
  src/constants/message/index.ts
  src/pages/404-page/404.js
  src/pages/_app.tsx
  src/pages/index.tsx
  src/styles/globals.css
Labels: feature

#14 [Feature] 사이드바&알람 스타일링
  public/assets/images/blue-dot.svg
  public/assets/images/close.svg
  public/assets/images/dumi-profile.png
  public/assets/images/my-info.svg
  public/assets/images/pen.svg
  public/assets/images/red-dot.svg
  public/assets/images/reserve-check.svg
  public/assets/images/reserve-info.svg
  public/assets/images/setting.svg
  src/components/Alarm/Alarm.module.scss
  src/components/Alarm/Alarm.tsx
  src/components/Header/Header.tsx
  src/components/SideBar/SideBar.module.scss
  src/components/SideBar/SideBar.tsx
  src/pages/index.tsx
  tsconfig.json
Labels: design

#15 404 page
  src/pages/404-page/404.js
  src/pages/404.tsx
  src/styles/404.module.scss
  src/styles/globals.css
Labels: design

#18 [Feat] 모달 공통컴포넌트 작성
  src/components/Button/Button.tsx
  src/components/Button/button.module.scss
  src/components/Modal/Modal.tsx
  src/components/Modal/ModalBase.tsx
  src/components/Modal/modalBase.module.scss
  src/types/.gitkeep
  src/types/type.ts
Labels: design

#27 [design] 체험 상세 페이지 퍼블리싱
  package-lock.json
  package.json
  public/assets/icons/Add.svg
  public/assets/icons/Subtract.svg
  public/assets/icons/arrow.png
  public/assets/images/location.svg
  public/assets/images/star.svg
  public/assets/images/test-map-mobile.png
  public/assets/images/test-map.png
  src/apis/activitiesApi.ts
  src/components/Footer/Footer.tsx
  src/components/Footer/footer.module.scss
  src/components/Header/Header.tsx
  src/components/Header/header.module.scss
  src/containers/DetailClass/DetailClass.tsx
  src/containers/DetailClass/detailClass.module.scss
  src/pages/_app.tsx
  src/styles/_variables.scss
Labels: design

#30 [Feat] 내 체험등록, 수정 페이지 디자인
  package-lock.json
  package.json
  public/assets/icons/delete-circle-btn.svg
  public/assets/icons/minus-time-btn.svg
  public/assets/icons/plus-time-btn.svg
  public/assets/icons/plus.svg
  public/assets/images/bird.jpg
  src/components/Layout/Layout.tsx
  src/components/MyClass/MyClassInputs/AddressInput/AddressInput.tsx
  src/components/MyClass/MyClassInputs/AddressInput/addressInput.module.scss
  src/components/MyClass/MyClassInputs/CategoryInput/CategoryInput.tsx
  src/components/MyClass/MyClassInputs/CategoryInput/categoryInput.module.scss
  src/components/MyClass/MyClassInputs/DateInput/DateInput.tsx
  src/components/MyClass/MyClassInputs/DateInput/DatedeleteInput.tsx
  src/components/MyClass/MyClassInputs/DateInput/dateDeleteInput.module.scss
  src/components/MyClass/MyClassInputs/DateInput/dateInput.module.scss
  src/components/MyClass/MyClassInputs/DescriptionInput/DescriptionInput.module.scss
  src/components/MyClass/MyClassInputs/DescriptionInput/DescriptionInput.tsx
  src/components/MyClass/MyClassInputs/ImageInput/ImageInput.tsx
  src/components/MyClass/MyClassInputs/ImageInput/SubImgaeInput.tsx
  src/components/MyClass/MyClassInputs/ImageInput/imageInput.module.scss
  src/components/MyClass/MyClassInputs/ImageInput/subImageInput.module.scss
  src/components/MyClass/MyClassInputs/PriceInput/PriceInput.tsx
  src/components/MyClass/MyClassInputs/PriceInput/priceInput.module.scss
  src/components/MyClass/MyClassInputs/TitleInput/TitleInput.tsx
  src/components/MyClass/MyClassInputs/TitleInput/titleInput.module.scss
  src/components/MyClass/MyClassInputs/input.module.scss
  src/components/MyClass/MyClassTitle/MyClassTitle.tsx
  src/components/MyClass/MyClassTitle/myClassTitle.module.scss
  src/pages/my-page/my-class/add-class/index.tsx
  src/styles/globals.css
Labels: design

#32 [Feat] 메인페이지 컴포넌트 퍼블리싱
  public/assets/icons/bed-icon.svg
  public/assets/icons/star-icon.svg
  src/components/mainPage/Banner/Banner.tsx
  src/components/mainPage/Banner/banner.module.scss
  src/components/mainPage/BestClassCard/BestClassCard.tsx
  src/components/mainPage/BestClassCard/bestClassCard.module.scss
  src/components/mainPage/ClassCard/ClassCard.tsx
  src/components/mainPage/ClassCard/classCard.module.scss
  src/components/mainPage/SearchBar/SearchBar.tsx
  src/components/mainPage/SearchBar/searchBar.module.scss
Labels: design

#34 [design] 예약 모달 퍼블리싱
  package-lock.json
  package.json
  public/assets/icons/close.svg
  src/components/DetailClass/DetailClass.tsx
  src/components/DetailClass/calendar/CalendarComponent.tsx
  src/components/DetailClass/calendar/calendarComponent.module.scss
  src/components/DetailClass/modal/Modal.tsx
  src/components/DetailClass/modal/modal.module.scss
  src/components/DetailClass/reservation/Reservation.tsx
  src/components/DetailClass/reservationModal/ReservationModal.tsx
  src/components/DetailClass/reservationModal/reservationModal.module.scss
Labels: design

#31 [Feat] input 공통컴포넌트 (ui 제외)
  package-lock.json
  package.json
  src/components/Input/Input.tsx
  src/components/Input/input.module.scss
  src/components/Layout/Layout.tsx
  src/containers/DetailClass/DetailClass.tsx
  src/containers/DetailClass/detailClass.module.scss
  src/containers/ProfileInfoChangeForm/ProfileInfoChangeForm.module.scss
  src/containers/ProfileInfoChangeForm/ProfileInfoChangeForm.tsx
  src/pages/index.tsx
  src/pages/my-page/profile-info/index.tsx
  src/styles/404.module.scss
  src/styles/globals.css
Labels: design, refactor
