Repository FE3-part4-team2/-Nomad, pull requests merged in 2024-05, with the labels that each got.

#38 [Hotfix] Eslint설정 변경 및 빌드 오류 수정
  .eslintrc.cjs
  package-lock.json
  package.json
  src/apis/activitiesApi.ts
  src/apis/dummy.ts
  src/components/DetailClass/DetailClass.tsx
  src/components/DetailClass/calendar/CalendarComponent.tsx
  src/components/DetailClass/modal/Modal.tsx
  src/components/DetailClass/reservation/Reservation.tsx
  src/components/DetailClass/reservationModal/ReservationModal.tsx
  src/components/Input/Input.tsx
  src/components/Layout/Layout.tsx
  src/components/MyClass/MyClassInputs/AddressInput/AddressInput.tsx
  src/components/MyClass/MyClassInputs/CategoryInput/CategoryInput.tsx
  src/components/MyClass/MyClassInputs/DateInput/DateInput.tsx
  src/components/MyClass/MyClassInputs/DateInput/DatedeleteInput.tsx
  src/components/MyClass/MyClassInputs/DescriptionInput/DescriptionInput.tsx
  src/components/MyClass/MyClassInputs/ImageInput/ImageInput.tsx
  src/components/MyClass/MyClassInputs/ImageInput/SubImgaeInput.tsx
  src/components/MyClass/MyClassInputs/PriceInput/PriceInput.tsx
  src/components/MyClass/MyClassInputs/TitleInput/TitleInput.tsx
  src/containers/ProfileInfoChangeForm/ProfileInfoChangeForm.tsx
  src/pages/404.tsx
  src/pages/my-page/profile-info/index.tsx
  src/utils/instance.ts
Labels: bug, hotfix, setting

#39 [Hotfix] 오류 수정
  src/components/DetailClass/modal/Modal.tsx
Labels: bug, hotfix

#40 [Hotfix] 임시로 빈 파일 채우기
  src/pages/class-info/[id]/index.tsx
  src/pages/my-page/index.tsx
  src/pages/my-page/manage-reservation/index.tsx
  src/pages/my-page/my-class/index.tsx
  src/pages/my-page/my-reservation/index.tsx
  src/pages/sign-in/index.tsx
  src/pages/sign-up/index.tsx
Labels: bug, hotfix

#48 [Design] 로그인/회원가입 페이지 퍼블리싱
  public/assets/icons/eye-off.svg
  public/assets/icons/logo-icon.svg
  public/assets/icons/logo2.svg
  src/components/Header/Header.tsx
  src/pages/sign-in/index.module.scss
  src/pages/sign-in/index.tsx
  src/pages/sign-up/index.module.scss
  src/pages/sign-up/index.tsx
Labels: design

#43 [Feat] 드랍다운, 케밥 props 수정
  src/components/DropDown/DropDown.tsx
  src/components/DropDown/DropDownList.tsx
  src/components/DropDown/Kebab.tsx
Labels: design

#49 💄[ Design] 캘린더 디자인
  package-lock.json
  package.json
  src/components/Calendar/Calendar.css
  src/components/Calendar/Calendar.tsx
  src/components/Select/Select.tsx
  src/components/Select/select.module.scss
  src/pages/_app.tsx
  src/pages/reserve-stat/index.module.scss
  src/pages/reserve-stat/index.tsx
Labels: feature, design

#50 [Feature] Header 수정
  public/assets/icons/default-user.png
  public/assets/icons/line.svg
  public/assets/icons/notification.svg
  src/apis/authApi.ts
  src/components/Header/Header.tsx
  src/components/Header/header.module.scss
  src/utils/instance.ts
Labels: feature

#51 🔧 [Setting] Api 세팅
  src/apis/axiosInstance.ts
  src/apis/getReservationDashboardApi.ts
  src/apis/myActivitiesApi.ts
  src/apis/postSignInApi.ts
  src/apis/postSignUpApi.ts
  src/components/DetailClass/DetailClass.tsx
  src/components/Select/Select.tsx
  src/containers/SelectCon/SelectCon.tsx
  src/pages/manage-reservation/index.module.scss
  src/pages/manage-reservation/index.tsx
  src/pages/reserve-stat/index.tsx
  src/utils/instance.ts
Labels: feature

#56 🔧 Setting: 리코일 세팅
  src/apis/authApi.ts
  src/apis/getReservationDashboardApi.ts
  src/components/Calendar/Calendar.tsx
  src/components/Select/Select.tsx
  src/containers/CalendarContainer/CalendarContainer.tsx
  src/containers/SelectContainer/SelectContainer.tsx
  src/pages/_app.tsx
  src/pages/manage-reservation/index.tsx
  src/store/idAtom.ts
Labels: setting

#55 [Feat] 메인페이지 퍼블리싱 및 일부 기능 추가
  package-lock.json
  src/apis/activitiesApi.ts
  src/apis/dummy.ts
  src/components/Button/Button.tsx
  src/components/Button/button.module.scss
  src/components/Footer/Footer.tsx
  src/components/Footer/footer.module.scss
  src/components/Header/Header.tsx
  src/components/Header/header.module.scss
  src/components/mainPage/Banner/banner.module.scss
  src/components/mainPage/BestClassCard/BestClassCard.tsx
  src/components/mainPage/BestClassCard/bestClassCard.module.scss
  src/components/mainPage/CategoryBar/CategoryBar.tsx
  src/components/mainPage/CategoryBar/categoryBar.module.scss
  src/components/mainPage/ClassCard/ClassCard.tsx
  src/components/mainPage/ClassCard/classCard.module.scss
  src/containers/mainPage/BestClassList/BestCardList.tsx
  src/containers/mainPage/BestClassList/bestCardList.module.scss
  src/containers/mainPage/ClassCardList/ClassCardList.tsx
  src/containers/mainPage/ClassCardList/classCardList.module.scss
  src/pages/index.module.scss
  src/pages/index.tsx
  src/styles/globals.css
Labels: feature, design

#57 [feature] 리뷰 무한스크롤 및 타입 파일 분리
  .eslintrc.cjs
  src/apis/activitiesApi.ts
  src/apis/axiosInstance.ts
  src/components/DetailClass/DetailClass.tsx
  src/components/DetailClass/calendar/CalendarComponent.tsx
  src/components/DetailClass/calendar/calendarComponent.module.scss
  src/components/DetailClass/classTitle/ClassTitle.tsx
  src/components/DetailClass/map/Map.tsx
  src/components/DetailClass/reservationModal/ReservationModal.tsx
  src/components/DetailClass/review_/Review.tsx
  src/components/DetailClass/review_/review.module.scss
  src/hooks/useObserver/useIntersectionObserver.ts
  src/pages/class-info/[id]/index.tsx
  src/types/activitiesType/ActivitiesType.ts
  src/types/authType/AuthType.ts
Labels: feature

#65 [Design] 캘린더 반응형 수정 및 자잘한 수정
  src/apis/activitiesApi.ts
  src/components/Calendar/Calendar.css
  src/components/Calendar/Calendar.tsx
  src/components/DetailClass/DetailClass.tsx
  src/components/DetailClass/classTitle/classTitle.module.scss
  src/components/DetailClass/description/description.module.scss
  src/components/DetailClass/modal/modal.module.scss
  src/components/DetailClass/reservation/Reservation.tsx
  src/components/DetailClass/reservation/reservation.module.scss
  src/components/DetailClass/reservationModal/ReservationModal.tsx
  src/components/DetailClass/reservationModal/reservationModal.module.scss
  src/components/DetailClass/review_/Review.tsx
  src/components/DetailClass/review_/review.module.scss
  src/components/Header/Header.tsx
  src/containers/ReservationCalendar/ReservationCalendar.tsx
  src/pages/class-info/[id]/index.tsx
  src/types/activitiesType/ActivitiesType.ts
Labels: design

#63 [Feat] 내 체험 등록 input 기능 구현
  package-lock.json
  package.json
  src/apis/activitiesApi.ts
  src/components/MyClass/MyClassInputs/AddressInput/AddressInput.tsx
  src/components/MyClass/MyClassInputs/AddressInput/addressInput.module.scss
  src/components/MyClass/MyClassInputs/CategoryInput/CategoryInput.tsx
  src/components/MyClass/MyClassInputs/DateInput/DateInput.tsx
  src/components/MyClass/MyClassInputs/DateInput/DatedeleteInput.tsx
  src/components/MyClass/MyClassInputs/DateInput/dateInput.module.scss
  src/components/MyClass/MyClassInputs/DescriptionInput/DescriptionInput.module.scss
  src/components/MyClass/MyClassInputs/DescriptionInput/DescriptionInput.tsx
  src/components/MyClass/MyClassInputs/ImageInput/ImageInput.tsx
  src/components/MyClass/MyClassInputs/ImageInput/SubImgaeInput.tsx
  src/components/MyClass/MyClassInputs/PriceInput/PriceInput.tsx
  src/components/MyClass/MyClassInputs/TitleInput/TitleInput.tsx
  src/components/MyClass/MyClassInputs/input.module.scss
  src/components/MyClass/MyClassTitle/MyClassTitle.tsx
  src/containers/ImageInput/ImageInputContainer.tsx
  src/containers/ImageInput/SubImageInputContainer.tsx
  src/types/activitiesType/ActivitiesType.ts
Labels: feature

#67 ✨[Feat] 캘린더 타일에 데이터삽입기능추가
  src/apis/getReservationsApi.ts
  src/apis/getReservedScheduleApi.ts
  src/apis/patchReservationsUpdateApi.ts
  src/apis/postSignInApi.ts
  src/components/Calendar/Calendar.tsx
  src/components/Select/Select.tsx
  src/containers/CalendarContainer/CalendarContainer.tsx
  src/store/atoms/idState.ts
Labels: feature

#70 [Feat] My resverations Card 컴포넌트 추가
  src/apis/getMyReservation.ts
  src/apis/myInfoApi.ts
  src/components/Input/Input.tsx
  src/components/Input/input.module.scss
  src/components/ReservationCard/ReservationCard.module.scss
  src/components/ReservationCard/ReservationCard.tsx
  src/containers/ProfileInfoChangeForm/ProfileInfoChangeForm.module.scss
  src/containers/ProfileInfoChangeForm/ProfileInfoChangeForm.tsx
  src/containers/ReservationCardContainer/ReservationCardContainer.tsx
  src/types/type.ts
Labels: feature, design

#71 [✨ Feat] 모달 베이스 컴포넌트&컨테이너 생성
  src/components/Modal2/Modal2Base.tsx
  src/components/Modal2/modal2Base.module.scss
  src/containers/ModalContainer/ModalContainer.tsx
  src/pages/manage-reservation/index.tsx
Labels: feature

#72 [Feat] 내 체험 생성하기 기능 구현
  src/apis/activitiesApi.ts
  src/components/MyClass/MyClassInputs/CategoryInput/CategoryInput.tsx
  src/components/MyClass/MyClassInputs/DateInput/DateInput.tsx
  src/components/MyClass/MyClassInputs/DateInput/DatedeleteInput.tsx
  src/components/MyClass/MyClassInputs/DateInput/dateInput.module.scss
  src/components/MyClass/MyClassInputs/ImageInput/SubImgaeInput.tsx
  src/components/MyClass/MyClassTitle/MyClassTitle.tsx
  src/containers/ImageInput/ImageInputContainer.tsx
  src/containers/ImageInput/SubImageInputContainer.tsx
  src/pages/my-page/my-class/add-class/index.tsx
  src/types/activitiesType/ActivitiesType.ts
Labels: feature

#73 [✨ Feat] 캘린더 모달 기능작업 완료
  src/apis/getReservationsApi.ts
  src/apis/patchReservationsUpdateApi.ts
  src/components/Calendar/123.tsx
  src/components/Calendar/Calendar.css
  src/components/Calendar/Calendar.tsx
  src/components/DetailClass/reservationModal/ReservationModal.tsx
  src/components/Modal2/ReserveInfoModal/ReserveInfoModal.tsx
  src/components/Modal2/modal2Base.module.scss
  src/components/Select/Select.tsx
  src/containers/CalendarContainer/CalendarContainer.tsx
  src/containers/ModalContainer/ModalContainer.tsx
  src/containers/SelectContainer/SelectContainer.tsx
  src/pages/manage-reservation/index.tsx
  src/pages/my-page/manage-reservation/index.module.scss
  src/pages/my-page/manage-reservation/index.tsx
  src/store/atoms/idState.ts
Labels: feature

#75 [Feat] 무한스크롤 및 슬라이딩 배너 구현
  package-lock.json
  package.json
  src/apis/activitiesApi.ts
  src/components/mainPage/Banner/Banner.tsx
  src/containers/mainPage/Banner/BannerContainer.tsx
  src/containers/mainPage/Banner/bannerContainer.module.scss
  src/containers/mainPage/CategoryBarContainer/CategoryBarContainer.tsx
  src/containers/mainPage/ClassCardList/ClassCardList.tsx
  src/pages/index.tsx
  src/store/atoms/paramStates.ts
  src/store/atoms/searchState.ts
Labels: feature

#76 [Design] 캘린더, 캘린더모달, 체험x페이지 스타일링 완료
  public/assets/images/empty-docs.svg
  src/apis/authApi.ts
  src/components/Calendar/123.tsx
  src/components/Calendar/Calendar.css
  src/components/Calendar/Calendar.tsx
  src/components/Header/Header.tsx
  src/components/Modal2/ReserveInfoModal/ReserveInfoModal.tsx
  src/components/Modal2/ReserveInfoModal/reserveInfoModal.module.scss
  src/components/Modal2/modal2Base.module.scss
  src/components/NoneExp/NoneExp.tsx
  src/components/NoneExp/noneExp.module.scss
  src/components/SideBar/SideBar.tsx
  src/containers/CalendarContainer/CalendarContainer.tsx
  src/containers/SelectContainer/SelectContainer.tsx
  src/pages/my-page/manage-reservation/index.tsx
  src/store/atoms/idState.ts
Labels: design

#79 My resverations
  src/apis/getMyReservation.ts
  src/apis/myInfoApi.ts
  src/components/ReservationCard/ReservationCard.module.scss
  src/components/ReservationCard/ReservationCard.tsx
  src/containers/ReservationCardContainer/ReservationCardContainer.tsx
  src/hooks/useWindowSize/index.ts
  src/pages/my-page/index.tsx
  src/pages/my-page/my-reservation/index.tsx
  src/types/type.ts
Labels: feature

#80 [Feat] 로그인/회원가입 페이지 컴포넌트화
  src/components/Input/AuthInput/AuthInput.tsx
  src/components/Input/AuthInput/authInput.module.scss
  src/components/logo/AuthLogoImage.tsx
  src/components/logo/authLogoImage.module.scss
  src/pages/sign-in/index.module.scss
  src/pages/sign-in/index.tsx
  src/pages/sign-up/index.module.scss
  src/pages/sign-up/index.tsx
Labels: refactor

#81 [Hotfix] 배포 오류 수정
  src/apis/myActivitiesApi.ts
  src/components/Calendar/Calendar.tsx
  src/components/Calendar/MiniCalendar/MiniCalendar.tsx
  src/components/DetailClass/miniCalendarContainer/MiniCalendarContainer.tsx
  src/components/DetailClass/modal/Modal.tsx
  src/components/Header/Header.tsx
  src/components/Input/Input.tsx
  src/components/Modal2/ReserveInfoModal/ReserveInfoModal.tsx
  src/containers/CalendarContainer/CalendarContainer.tsx
  src/containers/ReservationCalendar/ReservationCalendar.tsx
  src/containers/SelectContainer/SelectContainer.tsx
  src/containers/mainPage/ClassCardList/ClassCardAfterSearch.tsx
  src/pages/my-page/manage-reservation/index.tsx
  src/pages/my-page/my-reservation/index.tsx
Labels: hotfix

#85 [Feat][Style] : 반응형 완료 & 필터 기능 완
  src/apis/getMyReservation.ts
  src/components/DropDown/DropDown.tsx
  src/components/Header/Header.tsx
  src/components/ReservationCard/ReservationCard.module.scss
  src/components/ReservationCard/ReservationCard.tsx
  src/hooks/useWindowSize/index.ts
  src/pages/my-page/my-reservation/index.tsx
  src/pages/my-page/my-reservation/my-reservation.module.scss
Labels: feature, design

#86 [Feature] 상세페이지 자잘한 수정
  src/apis/authApi.ts
  src/apis/usersApi.ts
  src/components/Calendar/Calendar.css
  src/components/DetailClass/DetailClass.tsx
  src/components/DetailClass/classTitle/ClassTitle.tsx
  src/components/DetailClass/detailClass.module.scss
  src/components/DetailClass/image_/Image.tsx
  src/components/DetailClass/miniCalendarContainer/MiniCalendarContainer.tsx
  src/components/DetailClass/miniCalendarContainer/miniCalendarContainer.module.scss
  src/components/DetailClass/modal/modal.module.scss
  src/components/DetailClass/reservation/Reservation.tsx
  src/components/DetailClass/reservation/reservation.module.scss
  src/components/DetailClass/review_/review.module.scss
  src/components/DropDown/Kebab.tsx
  src/components/Header/Header.tsx
  src/store/atoms/userState.ts
  src/types/usersType/joinType.ts
Labels: feature

#88 [Feature] header 드롭다운 추가
  src/components/Header/Header.tsx
  src/components/Header/header.module.scss
Labels: feature

#89 [💄 Design] 알림컴포넌트완료, 기타 자잘한 스타일수정
  src/apis/deleteNoficationIdApi.ts
  src/apis/getMyNotificationsApi.ts
  src/components/Alarm/Alarm.module.scss
  src/components/Alarm/Alarm.tsx
  src/components/Calendar/Calendar.css
  src/components/Calendar/Calendar.tsx
  src/components/Header/Header.tsx
  src/components/Header/header.module.scss
  src/components/Layout/layout.module.css
  src/components/Modal2/ReserveInfoModal/ReserveInfoModal.tsx
  src/components/Modal2/ReserveInfoModal/reserveInfoModal.module.scss
  src/components/Modal2/modal2Base.module.scss
  src/components/SideBar/SideBar.module.scss
  src/components/SideBar/SideBar.tsx
  src/containers/AlarmContainer/AlarmContainer.tsx
  src/containers/AlarmContainer/alarmContainer.module.scss
  src/containers/CalendarContainer/CalendarContainer.tsx
  src/pages/my-page/manage-reservation/index.tsx
Labels: bug, feature, design

#90 [Feat] 내 체험 등록, 수정 페이지 api 에러 처리, 주소 input 오류 해결, 자잘한 디자인 수정
  src/apis/activitiesApi.ts
  src/apis/myActivitiesApi.ts
  src/components/MyClass/MyClassInputs/AddressInput/AddressInput.tsx
  src/components/MyClass/MyClassInputs/DateInput/DateInput.tsx
  src/components/MyClass/MyClassInputs/DateInput/DatedeleteInput.tsx
  src/components/MyClass/MyClassInputs/DateInput/EditDateDeleteInput.tsx
  src/components/MyClass/MyClassInputs/DateInput/EditDateInput.tsx
  src/components/MyClass/MyClassInputs/DateInput/dateDeleteInput.module.scss
  src/components/MyClass/MyClassInputs/DateInput/dateInput.module.scss
  src/components/MyClass/MyClassInputs/ImageInput/SubImgaeInput.tsx
  src/components/MyClass/MyClassModal.tsx
  src/components/MyClass/MyClassTitle/EditMyClass.tsx
  src/components/MyClass/MyClassTitle/MyClassTitle.tsx
  src/components/MyClass/myClassModal.module.scss
  src/containers/ImageInput/SubImageInputContainer.tsx
  src/containers/MyClass/MyClassContainer.tsx
  src/pages/my-page/my-class/edit-class/index.tsx
Labels: bug, feature, design

#93 [Feat] 내 체험 관리 페이지
  package-lock.json
  package.json
  src/apis/myActivitiesApi.ts
  src/components/MyClass/MyClassCard/MyClassCard.tsx
  src/components/MyClass/MyClassCard/myClassCard.module.scss
  src/pages/my-page/my-class/index.module.scss
  src/pages/my-page/my-class/index.tsx
  src/styles/globals.css
  src/types/activitiesType/MyActivityType.ts
Labels: feature, design

#94 [Feat] 메인페이지 정렬 기능구현 및 로고 추가
  public/assets/images/globallogo.png
  public/assets/images/iceBreaker.png
  public/assets/images/logo.png
  src/components/Header/Header.tsx
  src/components/Header/header.module.scss
  src/components/logo/AuthLogoImage.tsx
  src/components/mainPage/CategoryBar/CategoryBar.tsx
  src/components/mainPage/CategoryBar/categoryBar.module.scss
  src/containers/mainPage/BestClassList/BestCardList.tsx
  src/containers/mainPage/BestClassList/bestCardList.module.scss
  src/containers/mainPage/CategoryBarContainer/CategoryBarContainer.tsx
  src/containers/mainPage/ClassCardList/ClassCardList.tsx
  src/pages/search/index.tsx
  src/styles/_variables.scss
  src/types/type.ts
Labels: bug, feature, design

#95 [Feature] 로그인/회원가입 기능 구현
  src/apis/authApi.ts
  src/apis/usersApi.ts
  src/components/DetailClass/DetailClass.tsx
  src/components/DetailClass/classTitle/ClassTitle.tsx
  src/components/Header/Header.tsx
  src/components/Input/AuthInput/AuthInput.tsx
  src/pages/sign-in/index.tsx
  src/pages/sign-up/index.tsx
  src/store/atoms/userState.ts
Labels: feature

#96 [Fix] 에러 해결
  src/components/Header/Header.tsx
Labels: hotfix

#97 [Fix] header 액세스 토큰에 따라 다르게 리렌더링
  src/apis/axiosInstance.ts
  src/components/Header/Header.tsx
  src/components/Header/header.module.scss
Labels: bug

#99 [Feat] 내 체험 정보 수정 페이지에서 제험 아이디 받게 수정
  src/components/MyClass/MyClassTitle/EditMyClass.tsx
  src/containers/AlarmContainer/AlarmContainer.tsx
  src/pages/my-page/my-class/edit-class/[id]/index.tsx
  src/pages/my-page/my-class/edit-class/index.tsx
Labels: feature

#100 [Chore] 상세페이지 이미지 크기 줄임, 회원가입 유효성 검사 추가
  src/components/DetailClass/DetailClass.tsx
  src/components/DetailClass/classTitle/ClassTitle.tsx
  src/components/DetailClass/classTitle/classTitle.module.scss
  src/components/DetailClass/description/description.module.scss
  src/components/DetailClass/image_/Image.tsx
  src/components/DetailClass/image_/image.css
  src/components/DetailClass/image_/image.module.scss
  src/components/DetailClass/review_/review.module.scss
  src/components/Input/AuthInput/AuthInput.tsx
  src/pages/_app.tsx
  src/pages/sign-up/index.module.scss
  src/pages/sign-up/index.tsx
Labels: feature

#101 [Fix] 배너 하드코딩 데이터 수정 및 헤더 여백 수정
  public/assets/images/cat.jpg
  public/assets/images/fu.jpg
  public/assets/images/terarium.jpg
  src/components/DetailClass/detailClass.module.scss
  src/components/Header/header.module.scss
  src/components/mainPage/Banner/banner.module.scss
  src/containers/mainPage/Banner/BannerContainer.tsx
Labels: bug, design

#104 [Fix] 예약 안되는 에러 해결
  src/components/Calendar/MiniCalendar/MiniCalendar.tsx
  src/components/DetailClass/miniCalendarContainer/MiniCalendarContainer.tsx
  src/components/mainPage/BestClassCard/bestClassCard.module.scss
  src/components/mainPage/ClassCard/classCard.module.scss
Labels: hotfix

#105 [Hotfix] 3차 배포 오류 수정
  src/apis/getMyReservation.ts
  src/apis/myActivitiesApi.ts
  src/apis/usersApi.ts
  src/components/Alarm/Alarm.tsx
  src/components/Input/AuthInput/AuthInput.tsx
  src/components/Modal2/ReserveInfoModal/ReserveInfoModal.tsx
  src/pages/my-page/manage-reservation/index.tsx
  src/pages/sign-up/index.tsx
Labels: hotfix

#109 [Feat] 프로필 인포 변경 & 사이드바 프로필 이미지도 변경 완료!
  package-lock.json
  package.json
  src/apis/myInfoApi.ts
  src/components/SideBar/SideBar.tsx
  src/containers/ProfileInfoChangeForm/ProfileInfoChangeForm.module.scss
  src/containers/ProfileInfoChangeForm/ProfileInfoChangeForm.tsx
  src/pages/my-page/my-class/index.tsx
  src/store/atoms/userState.ts
Labels: feature, design

#110 [Hotfix] 배포 오류 수정
  src/components/SideBar/SideBar.tsx
  src/containers/ProfileInfoChangeForm/ProfileInfoChangeForm.tsx
Labels: hotfix

#112 ♻️ Refactor: 액세스토큰 쿠키처리,리프레쉬토큰 처리기능추가
  package-lock.json
  package.json
  src/apis/authApi.ts
  src/apis/axiosInstance.ts
  src/components/Header/Header.tsx
Labels: feature, refactor

#118 [Feat] 배너 링크 연결, 카테고리바 수정 등
  public/assets/icons/lignt-icon.png
  src/components/Button/button.module.scss
  src/components/DropDown/dropDownList.module.scss
  src/components/mainPage/Banner/Banner.tsx
  src/components/mainPage/BestClassCard/bestClassCard.module.scss
  src/components/mainPage/CategoryBar/categoryBar.module.scss
  src/components/mainPage/ClassCard/classCard.module.scss
  src/components/mainPage/SearchBar/SearchBar.tsx
  src/containers/mainPage/Banner/BannerContainer.tsx
  src/containers/mainPage/CategoryBarContainer/CategoryBarContainer.tsx
  src/containers/mainPage/ClassCardList/ClassCardList.tsx
Labels: bug, feature, design
