Repository FE3-part4-team2/-Nomad, pull requests merged in 2024-06, with the labels that each got.

#121 ♻️ Refactor: 예약현황 페이지 수정
  public/assets/images/none-alarm.svg
  src/components/Alarm/Alarm.module.scss
  src/components/Alarm/Alarm.tsx
  src/components/Header/Header.tsx
  src/components/Modal2/modal2Base.module.scss
  src/components/SideBar/SideBar.module.scss
Labels: design

#123 [Hotfix] 배포 오류 수정
  package-lock.json
  package.json
  src/components/Alarm/Alarm.tsx
  src/components/Modal2/ReserveInfoModal/ReserveInfoModal.tsx
  src/components/MyClass/MyClassInputs/ImageInput/ImageInput.tsx
  src/components/MyClass/MyClassTitle/EditMyClass.tsx
  src/containers/ImageInput/EditBannerImageInputContainer.tsx
  src/containers/ImageInput/ImageInputContainer.tsx
  src/pages/my-page/my-class/edit-class/[id]/index.tsx
Labels: hotfix

#127 ✨ chore : 달력 데이터 받아오기 수정 및 자잘한 수정
  src/apis/activitiesApi.ts
  src/components/Calendar/Calendar.css
  src/components/Calendar/MiniCalendar/MiniCalendar.tsx
  src/components/DetailClass/miniCalendarContainer/MiniCalendarContainer.tsx
  src/components/DetailClass/miniCalendarContainer/miniCalendarContainer.module.scss
  src/components/DetailClass/reservation/reservation.module.scss
  src/components/DetailClass/review_/review.module.scss
Labels: refactor

#129 ✨ Feat:다크모드 추가
  public/assets/images/moon.svg
  public/assets/images/sun.svg
  src/components/Alarm/Alarm.module.scss
  src/components/DarkModeToggle/DarkModeToggle.tsx
  src/components/DarkModeToggle/darkModeToggle.module.scss
  src/components/Header/Header.tsx
  src/components/Header/header.module.scss
  src/components/Layout/layout.module.css
  src/components/mainPage/ClassCard/classCard.module.scss
  src/components/mainPage/SearchBar/searchBar.module.scss
  src/pages/_app.tsx
  src/pages/my-page/my-class/index.module.scss
  src/styles/color.scss
  src/styles/globals.scss
  src/styles/themes.scss
Labels: feature

#130 [Refactor] 내 체험 수정하기 페이지 구현 완료
  src/components/MyClass/MyClassInputs/DateInput/EditDateDeleteInput.tsx
  src/components/MyClass/MyClassInputs/DateInput/EditDateInput.tsx
  src/components/MyClass/MyClassInputs/ImageInput/EditSubImageInput.tsx
  src/components/MyClass/MyClassInputs/ImageInput/ImageInput.tsx
  src/components/MyClass/MyClassTitle/EditMyClass.tsx
  src/containers/ImageInput/EditBannerImageInputContainer.tsx
  src/containers/ImageInput/EditSubImageInputContainer.tsx
  src/containers/ImageInput/ImageInputContainer.tsx
  src/pages/my-page/my-class/edit-class/[id]/index.tsx
Labels: bug, refactor

#132 배포
  README.md
  package-lock.json
  public/assets/images/moon.svg
  public/assets/images/sun.svg
  src/apis/activitiesApi.ts
  src/components/Alarm/Alarm.module.scss
  src/components/Calendar/Calendar.css
  src/components/Calendar/MiniCalendar/MiniCalendar.tsx
  src/components/DarkModeToggle/DarkModeToggle.tsx
  src/components/DarkModeToggle/darkModeToggle.module.scss
  src/components/DetailClass/miniCalendarContainer/MiniCalendarContainer.tsx
  src/components/DetailClass/miniCalendarContainer/miniCalendarContainer.module.scss
  src/components/DetailClass/reservation/reservation.module.scss
  src/components/DetailClass/review_/review.module.scss
  src/components/Header/Header.tsx
  src/components/Header/header.module.scss
  src/components/Layout/layout.module.css
  src/components/MyClass/MyClassInputs/DateInput/EditDateDeleteInput.tsx
  src/components/MyClass/MyClassInputs/DateInput/EditDateInput.tsx
  src/components/MyClass/MyClassInputs/ImageInput/EditSubImageInput.tsx
  src/components/MyClass/MyClassInputs/ImageInput/ImageInput.tsx
  src/components/MyClass/MyClassTitle/EditMyClass.tsx
  src/components/mainPage/ClassCard/classCard.module.scss
  src/components/mainPage/SearchBar/searchBar.module.scss
  src/containers/ImageInput/EditBannerImageInputContainer.tsx
  src/containers/ImageInput/EditSubImageInputContainer.tsx
  src/containers/ImageInput/ImageInputContainer.tsx
  src/containers/ReservationCalendar/ReservationCalendar.tsx
  src/pages/_app.tsx
  src/pages/my-page/my-class/edit-class/[id]/index.tsx
  src/pages/my-page/my-class/index.module.scss
  src/styles/color.scss
  src/styles/globals.scss
  src/styles/themes.scss
Labels: hotfix

#134 🐛 Fix: 다크모드 css수정
  src/components/DarkModeToggle/DarkModeToggle.tsx
  src/components/MyClass/MyClassCard/myClassCard.module.scss
  src/components/Select/select.module.scss
  src/containers/ProfileInfoChangeForm/ProfileInfoChangeForm.module.scss
Labels: bug, design

#135 [Style] 내 체험 등록하기의 예약가능시간 input디자인 변경
  public/assets/icons/calendar.svg
  public/assets/icons/chevron-down.svg
  src/components/MyClass/MyClassDropDown/DateDropDown.tsx
  src/components/MyClass/MyClassDropDown/PlusDateDropDown.tsx
  src/components/MyClass/MyClassDropDown/dateDropDown.module.scss
  src/components/MyClass/MyClassInputs/DateInput/DateInput.tsx
  src/components/MyClass/MyClassInputs/DateInput/DatedeleteInput.tsx
  src/components/MyClass/MyClassInputs/DateInput/dateInput.module.scss
  src/components/MyClass/MyClassTitle/MyClassTitle.tsx
Labels: design

#136 [Style] 사소한 스타일들 수정 및 최신순 정렬 추가
  src/components/mainPage/Banner/banner.module.scss
  src/components/mainPage/CategoryBar/CategoryBar.tsx
  src/containers/mainPage/Banner/bannerContainer.module.scss
  src/containers/mainPage/BestClassList/BestCardList.tsx
  src/containers/mainPage/CategoryBarContainer/CategoryBarContainer.tsx
  src/pages/index.module.scss
Labels: feature, design

#138 [Hotfix] 배포 오류 수정
  src/containers/mainPage/ClassCardList/ClassCardList.tsx
Labels: hotfix

#139 배포
  README.md
  public/assets/icons/calendar.svg
  public/assets/icons/chevron-down.svg
  src/components/DarkModeToggle/DarkModeToggle.tsx
  src/components/DetailClass/image_/Image.tsx
  src/components/DetailClass/image_/image.module.scss
  src/components/MyClass/MyClassCard/myClassCard.module.scss
  src/components/MyClass/MyClassDropDown/DateDropDown.tsx
  src/components/MyClass/MyClassDropDown/PlusDateDropDown.tsx
  src/components/MyClass/MyClassDropDown/dateDropDown.module.scss
  src/components/MyClass/MyClassInputs/DateInput/DateInput.tsx
  src/components/MyClass/MyClassInputs/DateInput/DatedeleteInput.tsx
  src/components/MyClass/MyClassInputs/DateInput/dateInput.module.scss
  src/components/MyClass/MyClassTitle/MyClassTitle.tsx
  src/components/Select/select.module.scss
  src/components/mainPage/Banner/banner.module.scss
  src/components/mainPage/CategoryBar/CategoryBar.tsx
  src/containers/ProfileInfoChangeForm/ProfileInfoChangeForm.module.scss
  src/containers/mainPage/Banner/bannerContainer.module.scss
  src/containers/mainPage/BestClassList/BestCardList.tsx
  src/containers/mainPage/CategoryBarContainer/CategoryBarContainer.tsx
  src/containers/mainPage/ClassCardList/ClassCardList.tsx
  src/pages/index.module.scss
Labels: hotfix
